.TH 6005.CW1.ME6G08 1 "February 23, 2012"
.SH NAME
6005.cw1.me6g08 \- Simple command line RSS reader to show the latest news stories from sources.
.SH SYNOPSIS
.B 6005.cw1.me6g08
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B 6005.cw1.me6g08
commands.
.PP
\fB6005.cw1.me6g08\fP is a program that accepts in RSS feeds and then prints out the newest items in those feeds. There are different options available to choose multiple feeds and also to read in a different number of items each time.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-\-feeds
Takes either one or more RSS feeds specified.
.TP
.B \-\-items
Specifies how many items to read from the feeds.
.TP
.B \-\-help
Provides additional detail on how to use the program.
.SH AUTHOR
6005.cw1.me6g08 was written by Mike Elkins.
.PP
This manual page was written by Mike Elkins <me6g08@ecs.soton.ac.uk>,
for the Debian project (and may be used by others).
